### ISSUE TITLE
[DB] ERD erstellen

### ISSUE THREAD

**Issue by MoritzStiller** [QBERT18/webshop#2]
Ein Entity-Relationship-Diagram für die Datenbankstruktur soll erstellt werden.

**Comment by MoritzStiller** [comment]
Das ERD wurde mit draw.io erstellt. Ich kann das XML hier leider nicht anhängen, ich packe es mal in unseren Google Drive-Ordner, falls wir es noch bearbeiten müssen.
![ERD Webshop-DB](https://user-images.githubusercontent.com/64078556/80101487-c324f800-8571-11ea-88dc-33f4f65d71ce.PNG)

**Comment by QBERT18** [comment]
Sehr schön. Vielleicht überlegt ihr euch mit Daniel schon Projekte und pack die mal rein. Bitte aber die Queries dokumentieren.
